typography_spectrum: 0.8104583567474037
color:
  brandStrength: 0.7731614150106907
  lightness: 0.04856375511735678
  saturation: 0.6317147547379136
  rhythmicContrast: 0.8143880895804614
  brandColors:
    - '#73603D'
    - '#BF8A49'
    - '#F2CA80'
    - '#5E5A59'
    - '#0D0D0D'
github: true
layout_spectrum: 0.08524365327320993
analytics:
  google: UA-88873723-1
author:
  name: Patrick Housen
  email: info@patrickhousen.com
  url: 'http://patrickhousen.com'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/32edb77f-9da3-4209-9f29-5b8e6962cfe9.png
name: Composing Grounds
url: 'http://patrickhousen.com'
navigation:
  - name: Soundcloud
    url: 'https://soundcloud.com/patrick-housen/'
    type: external
  - name: LinkedIn
    url: 'https://be.linkedin.com/in/patrick-housen-b297bbb'
    type: external
  - name: EPAS Blog
    url: 'http://epas.patrickhousen.com'
    type: external
title: Digital Portfolio
content: []
description: Just listen & hear me out
purpose:
  - type: external
    url: 'https://thegrid.ai/epas-blog-patrick-housen'
    label: EPAS blog
  - type: contact
    url: 'mailto:info@patrickhousen.com'
    label: Contact me
